# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /categories/随笔     # 博客首页展示文本/访问路径/自定义归档名称
  生活: /categories/生活           
  学习: /categories/学习
  关于我: /about

# SubNav
subnav:
  github: "http://github.com/lgbwust"
  weibo: "http://weibo.com/lgbwust"
  #rss: "#"
  zhihu: "http://zhihu.com/people/lgbwust"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true


# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
baidu_tongji: true
favicon: /favicon.png

#你的头像url
avatar: /img/my.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: lgbwust
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  新浪微博: http://weibo.com

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是一只小小鸟~~~